-- 1. Önce InitialCreate migration'ını history'ye ekle
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251120180225_InitialCreate', '9.0.11');

-- 2. BlogPostDocuments tablosunu oluştur
CREATE TABLE "BlogPostDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BlogPostId" integer NOT NULL,
    "FileName" character varying(200) NOT NULL,
    "FilePath" character varying(500) NOT NULL,
    "DisplayName" character varying(200),
    "Description" character varying(500),
    "FileSize" bigint NOT NULL,
    "FileType" character varying(100) NOT NULL,
    "DownloadCount" integer NOT NULL DEFAULT 0,
    "UploadedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_BlogPostDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BlogPostDocuments_BlogPosts_BlogPostId"
        FOREIGN KEY ("BlogPostId")
        REFERENCES "BlogPosts" ("Id")
        ON DELETE CASCADE
);

-- 3. Index oluştur
CREATE INDEX "IX_BlogPostDocuments_BlogPostId" ON "BlogPostDocuments" ("BlogPostId");

-- 4. AddBlogPostDocuments migration'ını history'ye ekle
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251120191009_AddBlogPostDocuments', '9.0.11');
